### ISSUE TITLE
Narrative Storyboard

### ISSUE THREAD

**Issue by kierandowns** [TeamMaigo/parry-possession#7]
Look at creating a short storyboard or wireframe for the key information we are looking to show to our players. (i.e., In Undertale you have a pre-game story slideshow describing Humans vs. Monsters and falling in the hole, then major information is in conversations. What is our content for story, rather than the mechanic)

Format can be in a word document, or in a flowchart graphic

- [x] Graphic completed (Jonas, Omer?, Any other writers)

**Comment by Struckdown** [comment]
Forgot to close the issue. We have the gist for now though.
