### ISSUE TITLE
Integrating a Sprite + Animation

### ISSUE THREAD

**Issue by kierandowns** [TeamMaigo/parry-possession#8]
Look at either reusing previous assets (Placeholder) or creating new assets to put in place of our current logo character. Also look at how sprite sheets work in Godot, and attempt to animate from it the basic cardinals (Up,Down,Left,Right). Don't be too concerned about hitboxes or anything like that right now, and we have to determine what actual resolution of sprites we want to use moving forward. 

- [x] Import a spritesheet (New or old)
- [x] Replace current logo character with items from spritesheet
- [x] integrate movement for (Up,Down,Left,Right)
- [x] Determine style and specifications for tiles, characters, and other assets.

**Comment by Struckdown** [comment]
Give me sprites and I'll handle the rest.

**Comment by Struckdown** [comment]
Specifications should still be figured out?
